name: Auto Zip and Release

on:
  push:
    branches: [ "main" ]

jobs:
  ZipAndRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read version from version.txt
        id: get_version
        run: |
          VERSION=$(cat version.txt | tr -d '[:space:]')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Using version: $VERSION"
      
      - name: Set file timestamps
        run: |
          cd Modules
          find . -exec touch -t 198002010000.00 {} \;
          
      - name: Zip Modules contents
        run: |
          cd Modules
          zip -r ../LSPosed-v1.9.2-it-${{ steps.get_version.outputs.VERSION }}-release.zip *
      
      - name: Upload Modules archive
        uses: actions/upload-artifact@v4
        with:
          name: LSPosed-v1.9.2-it-${{ steps.get_version.outputs.VERSION }}-release.zip
          path: Modules/
      
      - name: Upload to telegram
        if: github.event_name != 'pull_request'
        env:
          CHAT_ID: ${{ secrets.CHAT_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_URL: ${{ github.event.head_commit.url }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          TITLE: New push to github!
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          if [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
            pip3 install telethon
            
            python3 $GITHUB_WORKSPACE/scripts/bot.py LSPosed-v1.9.2-it-${{ steps.get_version.outputs.VERSION }}-release.zip
          else
            echo "BOT_TOKEN not set, skipping Telegram upload"
          fi