name: Auto Zip and Release

on:
  push:
    branches: [ "main" ]

jobs:
  ZipAndRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read version from version.txt
        id: get_version
        run: |
          VERSION=$(cat version.txt | tr -d '[:space:]')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Using version: $VERSION"
      
      - name: Set file timestamps
        run: |
          cd Modules
          find . -exec touch -t 198002010000.00 {} \;
      
      - name: Upload Modules archive
        uses: actions/upload-artifact@v4
        with:
          name: LSPosed-v1.9.2-it-${{ steps.get_version.outputs.VERSION }}-release.zip
          path: Modules/
      - name:Send to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ğŸš€ New Release Available!
            
            ğŸ“¦ Project: LSPosed-Fake
            ğŸ·ï¸ Version: v1.9.2-it-${{ steps.get_version.outputs.VERSION }}
            ğŸ“… Build Date: ${{ github.event.head_commit.timestamp }}
            
            ğŸ”— Download: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            Commit: ${{ github.event.head_commit.message }}
          document: LSPosed-v1.9.2-it-${{ steps.get_version.outputs.VERSION }}-release.zip